[target.wasm32-unknown-unknown]
runner = "wasm-bindgen-test-runner"


[target.wasm32-wasip1]
# for pure WASI environment:
runner = "wasmtime -S inherit-env"

# for WASI on the web (`js` feature enabled):
#runner = "wasm-bindgen-test-runner"
#rustflags = ["-Z", "wasi-exec-model=reactor"]


[target.wasm32-wasip1-threads]
# for pure WASI environment:
runner = "wasmtime -S threads -S inherit-env"

# for WASI on the web (`js` feature enabled):
# runner = "wasm-bindgen-test-runner"
# rustflags = ["-Z", "wasi-exec-model=reactor"]

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
