name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build with latest stable Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt-get update && sudo apt install libdbus-1-dev pkg-config
      - name: Install latest stable Rust
        run: rustup set profile default && rustup default stable && rustup update
      - name: Check code formatting
        run: cargo fmt -- --check
      - name: Build
        run: cargo build --features bluer,usb-device,usb-host,raw-speed-cli,dump --all-targets --quiet
      - name: Build documentation
        run: cargo doc --no-deps --quiet
      - name: Code analysis
        run: cargo clippy --features bluer,usb-device,usb-host,raw-speed-cli,dump --all-targets --quiet
      - name: Run tests (debug)
        run: cargo test --quiet
      - name: Run tests (release)
        run: cargo test --release --quiet
      - name: Run agg-speed
        run: |
          cargo build --quiet --release --bin agg-speed
          RUST_LOG=info cargo run --quiet --release --bin agg-speed -- server --tls --no-monitor --oneshot &
          sleep 1
          RUST_LOG=info cargo run --quiet --release --bin agg-speed -- client --tls --no-monitor --time 15 --tcp localhost
      - name: Security vulnerability audit
        run: |
          cargo install --quiet cargo-audit
          cargo audit --quiet

  build-windows:
    name: Build with latest stable Rust on Windows
    runs-on: windows-latest
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install latest stable Rust
        run: rustup set profile default && rustup default stable && rustup update
      - name: Build
        run: cargo build --exclude aggligator-transport-bluer --features usb-host,raw-speed-cli,dump --all-targets --quiet
      - name: Run tests (debug)
        run: cargo test --exclude aggligator-transport-bluer --quiet

  build-msrv:
    name: Build with minimum supported Rust versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt-get update && sudo apt install libdbus-1-dev pkg-config
      - name: Install Rust 1.80.0
        run: rustup toolchain install 1.80.0
      - name: Build aggligator and aggligator-util with Rust 1.80.0
        run: cargo +1.80.0 build --features bluer,usb-device,usb-host,raw-speed-cli,dump --all-targets --quiet
